services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
      image: redis
      container_name: redis
      hostname: redis
      environment:
          - ALLOW_EMPTY_PASSWORD=yes
      ports:
          - '6379:6379'
  redis-commander:
      depends_on:
          - redis
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
          - REDIS_HOSTS=local:redis:6379 # note: this has to be the port the redis container exposes.
      ports:
          - "8081:8081"

volumes:
  pgdata:
    driver: local